### ISSUE TITLE
App not compatible with the latest version of homestead

### ISSUE THREAD

**Issue by korirdennis** [lloricode/lumen-boilerplate#23]
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires php ^7.4 but your php version (8.0.1) does not satisfy that requirement.
  Problem 2
    - gmsantos/inspiring is locked to version v3.0.2 and an update of this package was not requested.
    - gmsantos/inspiring v3.0.2 requires php ^7.2 -> your php version (8.0.1) does not satisfy that requirement.

**Comment by lloricode** [comment]
Kindly give me your `homestead` and `settler` versions, then inside vagrant/homestead kindly give me also what PHP version you are using?

Then i think this is not affected by version of homestead, for my environment detail is i am using `settler 10.1.1` and homestead branch `20.04`, meaning i am using ubuntu 20.04 with PHP7.4 (as default)

If you are using homestead `v12` with settler `v11`, I think you need to run inside homestead/vagrant terminal `php74`
to change default PHP version to 7.4, because latest version as of yesterday is PHP8
see https://github.com/laravel/homestead/tree/v12.0.0

**Comment by lloricode** [comment]
then in your error message it says `but your php version (8.0.1) does not satisfy that requirement.`
meaning you are using PHP8.0.1

closing this issue since already know the problem

**Comment by lloricode** [comment]
Mark this as `enhancement`, since it was not tested with PHP >= ^8, or you can test it on your side if it working on latest PHP8 versions
