### ISSUE TITLE
composer fresh error

### ISSUE THREAD

**Issue by ajiehatajie** [lloricode/lumen-boilerplate#8]
Argument 1 passed to Symfony\Component\Process\Process::__construct() must   
  be of the type array, string given, called in /Users/pulsetribedev/Document  
  s/Projects/ajie/php/lumen-boilerplate/app/Console/Commands/GenerateDocument  
  ationCommand.php on line 148                                                 
           
PHP 7.4.5 (cli) (built: Apr 18 2020 01:32:31) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

**Comment by lloricode** [comment]
@ajiehatajie 
this is related with this https://github.com/lloricode/lumen-boilerplate/issues/7
I try to fix this issue with php7.4 sooner, 

just try to use php7.2.5 up or php7.3, since in said versions we have tested that on unit testing
https://github.com/lloricode/lumen-boilerplate/actions/runs/75009528

thanks for posting this issue

**Comment by lloricode** [comment]
check this testing on php7.4
https://github.com/lloricode/lumen-boilerplate/runs/576052874?check_suite_focus=true

and soon i will work this milestone 
https://github.com/lloricode/lumen-boilerplate/milestone/1
